### ISSUE TITLE
The application does not meet the requirement

### ISSUE THREAD

**Issue by PanidaRumriankit** [pannlnwza/ku-polls#48]
In Vision and Scope Main features, you write `Voting may be restricted to people with a KU login.` but the application does not seem to work like that. It does not have a sign up by email to identify the organization. You should edit the vision and scope or work on this part to meet the requirements. I know that it is 'maybe' but now is a time to release the last version so if you still don't have this maybe you should consider doing something about it.
Best regards.

**Comment by pannlnwza** [comment]
Fixed.
